/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/home/AboutSection.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/home/HeroSection.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconEpConnection: typeof import('~icons/ep/connection')['default']
    IconEpPicture: typeof import('~icons/ep/picture')['default']
    IconEpUser: typeof import('~icons/ep/user')['default']
    IconIcBaselineGroup: typeof import('~icons/ic/baseline-group')['default']
    IconIcFacebook: typeof import('~icons/ic/facebook')['default']
    IconIcInstagram: typeof import('~icons/ic/instagram')['default']
    IconIcLinkedin: typeof import('~icons/ic/linkedin')['default']
    IconMdiAccountGroup: typeof import('~icons/mdi/account-group')['default']
    IconMdiCalendar: typeof import('~icons/mdi/calendar')['default']
    IconMdiChatProcessing: typeof import('~icons/mdi/chat-processing')['default']
    IconMdiChatProcessingOutline: typeof import('~icons/mdi/chat-processing-outline')['default']
    IconMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IconMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IconMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IconMdiLocation: typeof import('~icons/mdi/location')['default']
    IconMdiMagicStaff: typeof import('~icons/mdi/magic-staff')['default']
    IconMdiMapLegend: typeof import('~icons/mdi/map-legend')['default']
    IconMdiMessage: typeof import('~icons/mdi/message')['default']
    IconMdiPhone: typeof import('~icons/mdi/phone')['default']
    IconMdiUserGroup: typeof import('~icons/mdi/user-group')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./components/home/ServicesSection.vue')['default']
    StatsSection: typeof import('./components/home/StatsSection.vue')['default']
    TestimonialsSection: typeof import('./components/home/TestimonialsSection.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
